### ISSUE TITLE
ENA Collateral is not working !

### ISSUE THREAD

**Issue by mizovsky2304** [symbioticfi/collateral#2]
![image](https://github.com/symbioticfi/collateral/assets/74463073/751c54f4-797e-46b6-9f75-610af8518179)
![Capture d’écran 2024-06-26 à 15 46 53](https://github.com/symbioticfi/collateral/assets/74463073/c9776f28-b228-4de4-9a28-cefb222d642a)

The $ENA collateral is not working, it's showing a red message

**Comment by 1kresh** [comment]
Thanks, it was a small issue on the front-end side, which is already fixed.
